### ISSUE TITLE
Choose colour scheme

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/mondey#105]
This is the current colour scheme:

![image](https://github.com/user-attachments/assets/4c4b2f58-f0da-4a56-81c8-a9ca777f436e)

The values can be edited here:

https://github.com/ssciwr/mondey/blob/d4ea8f85283c81e378988904473b4a3d4cd2e9b7/frontend/tailwind.config.ts#L24-L33

**Comment by Majapur1** [comment]
<img width="936" alt="Screenshot 2024-10-29 at 17 06 01" src="https://github.com/user-attachments/assets/2ab647ad-e49f-43ad-a390-941a443dec2d">

Hi! I have accidentally changed a file package.json on my cloned repo + pushed it and now I can't remove it from my request. Can I crate a pull request like this and you will just ignore package.json?

**Comment by lkeegan** [comment]
resolved by #139
