### ISSUE TITLE
Have a default image for Children?

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/mondey#152]
When the observer who adds the child does not add an explicit image, we could have a dummy avatar image that is displayed instead. Something like this perhaps: https://www.istockphoto.com/de/vektor/flache-vektorillustration-in-graustufen-avatar-benutzerprofil-personensymbol-gm2151669184-572745045?searchscope=image%2Cfilm

**Comment by lkeegan** [comment]
No default image
