### ISSUE TITLE
Visualisation plots/charts

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/mondey#153]
For the admin/research interace it would be nice to offer some basic visualisation of the data.

In particular for #133 it would be nice to show the old & new expected ages as lines on a plot of score vs age data points.

[unovis](https://unovis.dev/) looks like a nice option, which comes with a svelte version although they [don't yet support svelte 5](https://github.com/f5/unovis/issues/379)

**Comment by MaHaWo** [comment]
could be overkill, but vega/vega-lite could be an option too: https://www.npmjs.com/package/svelte-vega
Based on d3, it's very powerful, and has a json like description syntax. I didn´t look into it deeply yet...

**Comment by MaHaWo** [comment]
https://vega.github.io/vega/

**Comment by MaHaWo** [comment]
https://d3js.org/

**Comment by lkeegan** [comment]
https://www.layerchart.com/ might also be an option, provides relatively simply looking svelte components, built on top of layercake & d3

**Comment by lkeegan** [comment]
https://svend3r.dev/charts
