### ISSUE TITLE
[meta] component architecture

### ISSUE THREAD

**Issue by lkeegan** [ssciwr/mondey#31]
It would be nice to simplify our frontend code to
- reduce use of additional intermediate data structures
- make more use of components
- move validation logic from outer scope to inner scope, e.g. to allow validation of a single input fields as is modified

Taking ChildrenRegistration as an example, we could change this to only have a single data structure, which is what we initially get from the API, and what we send back (after modifying it) to the API (psuedocode):

The API provides a list of fields, e.g. 
```js
fields = [{label: 'Name', type: 'text', value: '', placeholder: 'Bitte eintragen', key: 'name', required: true}, {}, ...]
```
ChildrenRegistration iterates over them and displays a component for each item, where the component then modifies the `.value` key of the item:

```svelte
    ...
    {#each field as field}
        <FormInput data=field />
    {/each}
    ...
```

Where the FormInput component displays the relevant input component depending on the field type
```svelte
    ...
    {#if data.type=='text'}
        <Textarea bind:value=field.value />
    {:else if data.type=='image'}
        ...
    {/if}
    ...
```
The FormInput component can also contain validation code for that field, which can then e.g. add a green tick once it is valid without having to validate the entire form.

(If the FormInput component starts to get complicated, e.g. the validation logic is different for each input type, this can be further broken down into a separate component for each input type)

Then clicking the "submit" button in ChildrenRegistration just sends the same (modified) data structure back to the API

### derived issues

-  #39 
-  #40 
-  #41
-  #45 
- #65 
- #66

**Comment by MaHaWo** [comment]
Isn´t it one datastructure already?

**Comment by MaHaWo** [comment]
closed b/c done
