### ISSUE TITLE
Currently the user registration allows multiple users with the same name? 

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/mondey#41]
**Describe the bug**
see heading 

**To Reproduce**
Try to use same username but different  passwords --> works

**Expected behavior**
Should probably not allow the same user to register twice? 

**Screenshots or files**
If applicable, add screenshots/files to help explain your problem.

\*\*machine/OS:

**Additional context**

**Comment by lkeegan** [comment]
True - but this is logic that will be implemented in the backend - all the frontend needs to do is send the user registration info to the backend, and display the response to the user
